// Regenerates packages/messages/src/keys.generated.ts from en-GB.json: the MessageKey union and
// the MessageArgs map, with argument types read from the ICU syntax of each message.
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { CATALOGUE, GENERATED, flatten, readJson } from './lib.mjs';

const require = createRequire(new URL('../../packages/messages/package.json', import.meta.url));
const { parse, TYPE } = require('@formatjs/icu-messageformat-parser');

function argTypes(message) {
  const args = new Map();
  const note = (name, type) => {
    const existing = args.get(name);
    if (!existing || existing === 'string | number') args.set(name, type);
  };
  const walk = (elements) => {
    for (const el of elements) {
      switch (el.type) {
        case TYPE.argument:
          note(el.value, 'string | number');
          break;
        case TYPE.number:
          note(el.value, 'number');
          break;
        case TYPE.date:
        case TYPE.time:
          note(el.value, 'Date | number');
          break;
        case TYPE.select:
          note(el.value, 'string');
          for (const option of Object.values(el.options)) walk(option.value);
          break;
        case TYPE.plural:
          note(el.value, 'number');
          for (const option of Object.values(el.options)) walk(option.value);
          break;
        case TYPE.tag:
          note(el.value, '(chunks: string[]) => string');
          walk(el.children);
          break;
        default:
          break;
      }
    }
  };
  walk(parse(message));
  return args;
}

const flat = flatten(readJson(CATALOGUE));
const keys = Object.keys(flat).sort();
const lines = [];
lines.push('/* Generated by `pnpm messages:types` from en-GB.json. Do not edit by hand. */');
lines.push('');
lines.push('export type MessageKey =');
for (const k of keys) lines.push(`  | '${k}'`);
lines.push(';');
lines.push('');
lines.push('export interface MessageArgs {');
for (const k of keys) {
  const args = argTypes(flat[k]);
  if (args.size === 0) lines.push(`  '${k}': Record<string, never>;`);
  else lines.push(`  '${k}': { ${[...args.entries()].map(([n, t]) => `${n}: ${t}`).join('; ')} };`);
}
lines.push('}');
lines.push('');
lines.push(`export const MESSAGE_KEYS: readonly MessageKey[] = [${keys.map((k) => `'${k}'`).join(', ')}];`);
lines.push('');
writeFileSync(GENERATED, lines.join('\n'));
console.log(`messages:types wrote ${keys.length} keys to keys.generated.ts`);
