'use client';

import { tKey, useT } from '@mas/messages';
import { useCallback } from 'react';

/**
 * Turns a refusal from the write pipeline into something a person can read.
 *
 * The pipeline returns codes rather than sentences on purpose. It runs in the store, has no
 * translator to hand and no business having one: a refusal is a fact about the record, not a piece
 * of copy, and the same refusal has to be assertable in a unit test without a React tree around it.
 * So the codes stay stable and the wording lives here, next to the screens that show it.
 *
 * Anything unrecognised is passed through rather than swallowed. A Zod issue arrives as
 * `path: message` and reads well enough; a code nobody has worded yet should appear on screen ugly
 * rather than disappear, because a refusal a practitioner cannot see is a Save button that does
 * nothing.
 */
const KEYS = [
  'noUser',
  'actionDueRequired',
  'actionIncomplete',
  'actionProcessRequired',
  'actionTitleRequired',
  'addendumNowRecordedRequired',
  'addendumRecordedRequired',
  'addressMissing',
  'advocacyRequired',
  'agenciesRequired',
  'alertEndsBeforeStart',
  'alertScopeRequired',
  'alertTextRequired',
  'alreadyMember',
  'alreadyRecordedInError',
  'applicantRequired',
  'applicationNotOpened',
  'areaRequired',
  'assigneeExcluded',
  'assigneeMissing',
  'assigneeNoAccess',
  'assigneeOversight',
  'assigneeRoleEmpty',
  'attendanceRequired',
  'attendeesRequired',
  'attorneyRequired',
  'cancelReasonRequired',
  'capacityAssessmentRequired',
  'capacityRequired',
  'caseHasNoOrder',
  'chairRequired',
  'changeNoteRequired',
  'childRequired',
  'childViewsRequired',
  'chiNeedsDateOfBirth',
  'classificationDowngrade',
  'closureNoteRequired',
  'closureReasonRequired',
  'concernsRequired',
  'conferenceNotHeld',
  'connectorRefusesIntent',
  'consentNoteRequired',
  'consentRequired',
  'contributionsRequired',
  'coordinatorRequired',
  'coreGroupRequired',
  'courtRequired',
  'cppmNotScheduled',
  'dateOfBirthFuture',
  'dateRequired',
  'deathAlreadyRecorded',
  'deathBeforeBirth',
  'deathInFuture',
  'deathNoteRequired',
  'deregistrationReasonRequired',
  'disclosureFactRequired',
  'disclosureRationaleRequired',
  'disclosureRecipientRequired',
  'documentEmpty',
  'documentNameRequired',
  'documentParentMissing',
  'documentRecordFull',
  'documentTooLarge',
  'documentTypeRequired',
  'dsdasRequired',
  'exitKindRequired',
  'expectedDeliveryPast',
  'expiryRequired',
  'guardianRequired',
  'holderRequired',
  'holdFormPending',
  'householdAlreadyMember',
  'householdEndReasonRequired',
  'householdExists',
  'householdLabelRequired',
  'householdMissing',
  'householdNotAMember',
  'identityReasonRequired',
  'inboundAlreadyReviewed',
  'inboundDeclineReasonRequired',
  'inboundMissing',
  'inboundNoSubject',
  'inboundNoType',
  'informationSharedRequired',
  'inquiryActionRequired',
  'inquiryNotOpened',
  'intervieweeRequired',
  'investigationDecisionRequired',
  'investigationInFuture',
  'investigationNotOpened',
  'investigationSummaryRequired',
  'invitationDeclineReasonRequired',
  'invitationMissing',
  'inviteesRequired',
  'involvementAmendReasonRequired',
  'involvementDecided',
  'involvementExcluded',
  'involvementMissing',
  'involvementNotPending',
  'involvementNotYours',
  'involvementPending',
  'involvementReasonRequired',
  'irdNotConvened',
  'irdTripartiteRequired',
  'jiiDecisionRequired',
  'lawfulBasisRequired',
  'leadProfessionalRequired',
  'leadReasonRequired',
  'leadSameUser',
  'leadWrongAgency',
  'leadWrongRole',
  'levelRequired',
  'lsiAlreadyOpen',
  'lsiChairSeniorityRequired',
  'lsiNotOpen',
  'mappaMeetingRequired',
  'mappaNotLevel1',
  'mappaNotReferred',
  'maracMeetingRequired',
  'maracNotHeard',
  'maracPlanRequired',
  'matacRequired',
  'medicalDecisionRequired',
  'medicalKindRequired',
  'meetingCancelReasonRequired',
  'meetingDateRequired',
  'meetingHeldByTransition',
  'meetingLocationRequired',
  'meetingMissing',
  'meetingNotScheduled',
  'meetingRequired',
  'meetingWrongStage',
  'mergeOtherMissing',
  'mergeReasonRequired',
  'mergeSameRecord',
  'mergeSurvivorMissing',
  'mhoRequired',
  'minuteNotApproved',
  'moveDateRequired',
  'moveNobodyMoving',
  'moveSameAddress',
  'nameRequired',
  'newExpiryRequired',
  'noChildrenOnReferral',
  'noInvestigationRouteRequired',
  'noResearchOutstanding',
  'noReturnsOutstanding',
  'noteRequired',
  'nothingChanged',
  'notPreBirth',
  'notRegistered',
  'orderRationaleRequired',
  'orderRequired',
  'outboxLawfulBasisRequired',
  'outboxMissing',
  'outboxNotAuthorisable',
  'outboxPurposeRequired',
  'outcomeRequired',
  'parentsDecisionRequired',
  'parentsExcludedReasonRequired',
  'parentsWithheldReasonRequired',
  'payloadEmpty',
  'payloadUnknownField',
  'personMissing',
  'planCoordinatorRequired',
  'planOutcomeRequired',
  'planRequired',
  'planTitleRequired',
  'powersNotChecked',
  'powersRequired',
  'practitionerRequired',
  'processAlreadyClosed',
  'processAlreadyOpen',
  'processMissing',
  'processNoSubject',
  'processNotClosed',
  'processNotEligible',
  'processNotOpen',
  'processNotYourRole',
  'progressRequired',
  'proportionalityRequired',
  'providerRequired',
  'purposeRequired',
  'rationaleRequired',
  'reasonRequired',
  'recordMissing',
  'recordsRequired',
  'referenceRequired',
  'referralFieldNotCorrectable',
  'referralUnchanged',
  'registerNameRequired',
  'registerReasonRequired',
  'relationshipDuplicate',
  'relationshipEndBeforeStart',
  'relationshipEndReasonRequired',
  'relationshipExclusionUndecided',
  'relationshipMissing',
  'relationshipPersonMissing',
  'relationshipSelf',
  'reopenReasonRequired',
  'reporterDecisionRequired',
  'requestMissing',
  'rescheduleReasonRequired',
  'reviewDateRequired',
  'riskAssessmentRequired',
  'riskDiscussionRequired',
  'routeNotApplication',
  'routeRequired',
  's13zaObjection',
  's13zaRequired',
  'scheduleRequired',
  'screeningAlreadyRecorded',
  'screeningNotProceed',
  'searchRequired',
  'settingRequired',
  'sharesNeedLawfulBasis',
  'sharesNeedProcess',
  'significantHarmDecisionRequired',
  'subjectRequired',
  'submissionAlreadyRecorded',
  'submissionDateInFuture',
  'submissionDateRequired',
  'submissionNotYours',
  'submissionRecipientRequired',
  'substituteExcluded',
  'substituteRequired',
  'substituteSameAgency',
  'substituteSelf',
  'summaryRequired',
  'supervisingOfficerRequired',
  'threePointTestRequired',
  'transitionMissing',
  'transitionNoAccess',
  'transitionNotFromThisStage',
  'transitionNotYourRole',
  'transitionWrongProcess',
  'unduePressureRequired',
  'unmergeAlreadyUndone',
  'unmergeMissing',
  'unmergeReasonRequired',
  'victimConsiderationsRequired',
  'visitInFuture',
  'visitSummaryRequired',
  'visitVisitorRequired',
  'willAndPreferencesRequired',
  'wordingRequired',
] as const;

export type WriteErrorCode = (typeof KEYS)[number];

const EXCLUDED = 'excluded:';

export function writeErrorText(code: string): string {
  if (code.startsWith(EXCLUDED)) return tKey('errors.write.excluded', { name: code.slice(EXCLUDED.length) });
  return (KEYS as readonly string[]).includes(code) ? tKey(`errors.write.${code}`) : code;
}

/**
 * The same, as a hook, for the common case of a list on a dialog.
 *
 * It subscribes to the translator without calling it, which looks redundant and is not: the
 * catalogue can be overridden from the Admin copy screen at runtime, and subscribing here is what
 * re-renders the dialog when somebody rewords a refusal.
 */
export function useWriteErrors(): (codes: string[]) => string[] {
  useT();
  return useCallback((codes: string[]) => codes.map(writeErrorText), []);
}
