import type { Organisation, Team, User } from '@mas/domain';
import type { BuildContext } from './context';

export const ORG = {
  council: 'org_council',
  hscp: 'org_hscp',
  nhs: 'org_nhs',
  police: 'org_police',
  womensAid: 'org_womens_aid',
  advocacy: 'org_advocacy',
  sps: 'org_sps',
  scra: 'org_scra',
  court: 'org_court',
  careInspectorate: 'org_care_inspectorate',
  opg: 'org_opg',
  mwc: 'org_mwc',
  fire: 'org_fire',
  cops: 'org_copfs',
} as const;

const organisations: Organisation[] = [
  { id: ORG.council, synthetic: true, kind: 'council', name: 'Clydeshore Council', shortName: 'Clydeshore Council' },
  { id: ORG.hscp, synthetic: true, kind: 'hscp', name: 'Clydeshore Health and Social Care Partnership', shortName: 'Clydeshore HSCP' },
  { id: ORG.nhs, synthetic: true, kind: 'health-board', name: 'NHS Clydeshore', shortName: 'NHS Clydeshore' },
  { id: ORG.police, synthetic: true, kind: 'police', name: 'Police Scotland, Z Division', shortName: 'Police Scotland' },
  { id: ORG.womensAid, synthetic: true, kind: 'third-sector', name: "Clydeshore Women's Aid", shortName: "Women's Aid" },
  { id: ORG.advocacy, synthetic: true, kind: 'third-sector', name: 'Clydeshore Advocacy', shortName: 'Advocacy' },
  { id: ORG.sps, synthetic: true, kind: 'sps', name: 'Scottish Prison Service, HMP Glenmoray', shortName: 'SPS' },
  { id: ORG.scra, synthetic: true, kind: 'scra', name: "Scottish Children's Reporter Administration, Clydeshore", shortName: 'SCRA' },
  { id: ORG.court, synthetic: true, kind: 'court', name: 'Ardvale Sheriff Court', shortName: 'Sheriff court' },
  { id: ORG.careInspectorate, synthetic: true, kind: 'regulator', name: 'Care Inspectorate', shortName: 'Care Inspectorate' },
  { id: ORG.opg, synthetic: true, kind: 'regulator', name: 'Office of the Public Guardian (Scotland)', shortName: 'OPG' },
  { id: ORG.mwc, synthetic: true, kind: 'regulator', name: 'Mental Welfare Commission for Scotland', shortName: 'MWC' },
  { id: ORG.fire, synthetic: true, kind: 'fire-rescue', name: 'Scottish Fire and Rescue Service, Clydeshore', shortName: 'Fire and rescue' },
  { id: ORG.cops, synthetic: true, kind: 'court', name: 'Procurator Fiscal, Ardvale', shortName: 'Procurator fiscal' },
];

export const TEAM = {
  childrenArdvale: 'team_children_ardvale',
  adultsPortnellan: 'team_adults_portnellan',
  adultProtection: 'team_adult_protection',
  mho: 'team_mho',
  justice: 'team_justice',
  publicProtectionCouncil: 'team_pp_council',
  reviewing: 'team_reviewing',
  housing: 'team_housing',
  ardvalePrimary: 'team_ardvale_primary',
  cswo: 'team_cswo',
  ppu: 'team_ppu',
  dau: 'team_dau',
  som: 'team_som',
  concernHub: 'team_concern_hub',
  cpHealth: 'team_cp_health',
  portnellanGp: 'team_portnellan_gp',
  healthVisiting: 'team_health_visiting',
  midwifery: 'team_midwifery',
  cmht: 'team_cmht',
  discharge: 'team_discharge',
  caldicott: 'team_caldicott',
  womensAid: 'team_womens_aid',
  advocacy: 'team_advocacy',
  spsSocialWork: 'team_sps_sw',
  apc: 'team_apc',
  cpc: 'team_cpc',
  inspection: 'team_inspection',
  admin: 'team_admin',
  scra: 'team_scra',
  ci: 'team_ci',
  opg: 'team_opg',
  mwc: 'team_mwc',
  fire: 'team_fire',
  pf: 'team_pf',
} as const;

const teams: Team[] = [
  { id: TEAM.childrenArdvale, organisationId: ORG.council, name: 'Children and Families, Ardvale', base: 'Ardvale Civic Centre' },
  { id: TEAM.adultsPortnellan, organisationId: ORG.hscp, name: 'Adult Services, Portnellan', base: 'Portnellan Resource Centre' },
  { id: TEAM.adultProtection, organisationId: ORG.hscp, name: 'Adult Protection Team', base: 'Portnellan Resource Centre' },
  { id: TEAM.mho, organisationId: ORG.hscp, name: 'Mental Health Officer Service', base: 'Kilbrannan Health and Care Hub' },
  { id: TEAM.justice, organisationId: ORG.council, name: 'Justice Social Work', base: 'Kilbrannan Justice Centre' },
  { id: TEAM.publicProtectionCouncil, organisationId: ORG.council, name: 'Public Protection Coordination', base: 'Ardvale Civic Centre' },
  { id: TEAM.reviewing, organisationId: ORG.council, name: 'Independent Reviewing Service', base: 'Ardvale Civic Centre' },
  { id: TEAM.housing, organisationId: ORG.council, name: 'Housing Options, Ardvale', base: 'Ardvale Housing Office' },
  { id: TEAM.ardvalePrimary, organisationId: ORG.council, name: 'Ardvale Primary School', base: 'Ardvale Primary School' },
  { id: TEAM.cswo, organisationId: ORG.council, name: 'Office of the Chief Social Work Officer', base: 'Ardvale Civic Centre' },
  { id: TEAM.ppu, organisationId: ORG.police, name: 'Public Protection Unit, Ardvale', base: 'Ardvale Police Station' },
  { id: TEAM.dau, organisationId: ORG.police, name: 'Domestic Abuse Investigation Unit', base: 'Ardvale Police Station' },
  { id: TEAM.som, organisationId: ORG.police, name: 'Sex Offender Policing Unit', base: 'Kilbrannan Police Station' },
  { id: TEAM.concernHub, organisationId: ORG.police, name: 'Concern Hub', base: 'Ardvale Police Station' },
  { id: TEAM.cpHealth, organisationId: ORG.nhs, name: 'Child Protection Health Team', base: 'Clydeshore Royal Infirmary' },
  { id: TEAM.portnellanGp, organisationId: ORG.nhs, name: 'Portnellan Medical Practice', base: 'Portnellan Medical Practice' },
  { id: TEAM.healthVisiting, organisationId: ORG.nhs, name: 'Health Visiting, Braeside', base: 'Braeside Health Centre' },
  { id: TEAM.midwifery, organisationId: ORG.nhs, name: 'Community Midwifery', base: 'Clydeshore Royal Infirmary' },
  { id: TEAM.cmht, organisationId: ORG.nhs, name: 'Community Mental Health Team, Kilbrannan', base: 'Kilbrannan Health and Care Hub' },
  { id: TEAM.discharge, organisationId: ORG.nhs, name: 'Discharge Coordination', base: 'Clydeshore Royal Infirmary' },
  { id: TEAM.caldicott, organisationId: ORG.nhs, name: 'Information Governance', base: 'NHS Clydeshore Headquarters' },
  { id: TEAM.womensAid, organisationId: ORG.womensAid, name: 'IDAA Service', base: 'Ardvale (confidential address)' },
  { id: TEAM.advocacy, organisationId: ORG.advocacy, name: 'Independent Advocacy', base: 'Kilbrannan' },
  { id: TEAM.spsSocialWork, organisationId: ORG.sps, name: 'Prison-based Social Work', base: 'HMP Glenmoray' },
  { id: TEAM.apc, organisationId: ORG.council, name: 'Adult Protection Committee', base: 'Ardvale Civic Centre' },
  { id: TEAM.cpc, organisationId: ORG.council, name: 'Child Protection Committee', base: 'Ardvale Civic Centre' },
  { id: TEAM.inspection, organisationId: ORG.careInspectorate, name: 'Joint Inspection Team', base: 'Care Inspectorate' },
  { id: TEAM.admin, organisationId: ORG.council, name: 'Digital Services', base: 'Ardvale Civic Centre' },
  { id: TEAM.scra, organisationId: ORG.scra, name: "Reporter's Office, Clydeshore", base: 'Ardvale' },
  { id: TEAM.ci, organisationId: ORG.careInspectorate, name: 'Adult Services Inspection', base: 'Care Inspectorate' },
  { id: TEAM.opg, organisationId: ORG.opg, name: 'Investigations', base: 'Office of the Public Guardian' },
  { id: TEAM.mwc, organisationId: ORG.mwc, name: 'Practitioners', base: 'Mental Welfare Commission' },
  { id: TEAM.fire, organisationId: ORG.fire, name: 'Community Safety', base: 'Glenmoray Fire Station' },
  { id: TEAM.pf, organisationId: ORG.cops, name: 'Ardvale', base: 'Ardvale Sheriff Court' },
];

export const USR = {
  janetKerr: 'usr_janet_kerr',
  moiraGilmour: 'usr_moira_gilmour',
  graemeDunlop: 'usr_graeme_dunlop',
  anneHendry: 'usr_anne_hendry',
  stuartBlair: 'usr_stuart_blair',
  helenRae: 'usr_helen_rae',
  rossMowat: 'usr_ross_mowat',
  karenFindlay: 'usr_karen_findlay',
  davidLaird: 'usr_david_laird',
  lesleyMorton: 'usr_lesley_morton',
  markHepburn: 'usr_mark_hepburn',
  claireCowan: 'usr_claire_cowan',
  andrewMuirhead: 'usr_andrew_muirhead',
  samOgilvie: 'usr_sam_ogilvie',
  elspethGunn: 'usr_elspeth_gunn',
  neilBaird: 'usr_neil_baird',
  paulMackay: 'usr_paul_mackay',
  ewanSutherland: 'usr_ewan_sutherland',
  priyaSharif: 'usr_priya_sharif',
  gavinBrodie: 'usr_gavin_brodie',
  fionaRoss: 'usr_fiona_ross',
  amiraFarouk: 'usr_amira_farouk',
  sunitaRao: 'usr_sunita_rao',
  kasiaNowicka: 'usr_kasia_nowicka',
  louiseKennedy: 'usr_louise_kennedy',
  heatherAitken: 'usr_heather_aitken',
  niallFyfe: 'usr_niall_fyfe',
  sadiaQureshi: 'usr_sadia_qureshi',
  erinLamont: 'usr_erin_lamont',
  tamGuthrie: 'usr_tam_guthrie',
  colinBeattie: 'usr_colin_beattie',
  rhonaDewar: 'usr_rhona_dewar',
  islaCrawford: 'usr_isla_crawford',
  morvenTait: 'usr_morven_tait',
  alistairMeek: 'usr_alistair_meek',
  jeanHogg: 'usr_jean_hogg',
  gordonNairn: 'usr_gordon_nairn',
  fionaLyle: 'usr_fiona_lyle',
} as const;

type UserSeed = Omit<User, 'synthetic' | 'email' | 'phone' | 'caseMemberships'> & { caseMemberships?: string[] };

function email(given: string, family: string, org: string): string {
  const domain: Record<string, string> = {
    [ORG.council]: 'clydeshore.gov.example',
    [ORG.hscp]: 'clydeshore-hscp.example',
    [ORG.nhs]: 'nhs-clydeshore.example',
    [ORG.police]: 'police-z.example',
    [ORG.womensAid]: 'clydeshore-womensaid.example',
    [ORG.advocacy]: 'clydeshore-advocacy.example',
    [ORG.sps]: 'sps.example',
    [ORG.scra]: 'scra.example',
    [ORG.court]: 'court.example',
    [ORG.careInspectorate]: 'careinspectorate.example',
    [ORG.opg]: 'opg.example',
    [ORG.mwc]: 'mwc.example',
    [ORG.fire]: 'sfrs.example',
    [ORG.cops]: 'copfs.example',
  };
  return `${given}.${family}@${domain[org] ?? 'example.invalid'}`.toLowerCase();
}

const seeds: UserSeed[] = [
  { id: USR.janetKerr, givenName: 'Janet', familyName: 'Kerr', agency: 'social-work', roleId: 'social-worker-children', jobTitle: 'Social worker, children and families', organisationId: ORG.council, teamId: TEAM.childrenArdvale, base: 'Ardvale Civic Centre', processMemberships: ['cp', 'marac'], blurb: 'Allocated worker for Aiden Boyle and the Docherty children.', featured: true },
  { id: USR.moiraGilmour, givenName: 'Moira', familyName: 'Gilmour', agency: 'social-work', roleId: 'council-officer-asp', jobTitle: 'Council officer, adult protection', organisationId: ORG.hscp, teamId: TEAM.adultProtection, base: 'Portnellan Resource Centre', processMemberships: ['asp', 'awi'], blurb: 'Council officer on the Fraser, Nowak and Rowanbank inquiries.', featured: true },
  { id: USR.graemeDunlop, givenName: 'Graeme', familyName: 'Dunlop', agency: 'social-work', roleId: 'mho', jobTitle: 'Mental Health Officer', organisationId: ORG.hscp, teamId: TEAM.mho, base: 'Kilbrannan Health and Care Hub', processMemberships: ['awi', 'asp'], blurb: 'MHO report for Ishbel Grant; capacity work with Marion Fraser.' },
  { id: USR.anneHendry, givenName: 'Anne', familyName: 'Hendry', agency: 'social-work', roleId: 'team-leader', jobTitle: 'Team leader, children and families', organisationId: ORG.council, teamId: TEAM.childrenArdvale, base: 'Ardvale Civic Centre', processMemberships: ['cp', 'marac'], blurb: 'Social work decision maker at IRDs.' },
  { id: USR.stuartBlair, givenName: 'Stuart', familyName: 'Blair', agency: 'social-work', roleId: 'social-worker-adults', jobTitle: 'Social worker, adults', organisationId: ORG.hscp, teamId: TEAM.adultsPortnellan, base: 'Portnellan Resource Centre', processMemberships: ['asp', 'awi'], blurb: 'Allocated worker for Ishbel Grant and Tomasz Nowak.' },
  { id: USR.helenRae, givenName: 'Helen', familyName: 'Rae', agency: 'social-work', roleId: 'justice-social-worker', jobTitle: 'Justice social worker', organisationId: ORG.council, teamId: TEAM.justice, base: 'Kilbrannan Justice Centre', processMemberships: ['mappa', 'marac'], blurb: 'Supervises Derek Muir on licence and Ryan Kerr on a community order.' },
  { id: USR.rossMowat, givenName: 'Ross', familyName: 'Mowat', agency: 'social-work', roleId: 'mappa-coordinator', jobTitle: 'MAPPA Coordinator', organisationId: ORG.council, teamId: TEAM.publicProtectionCouncil, base: 'Ardvale Civic Centre', processMemberships: ['mappa'], blurb: 'Coordinates Level 2 and 3 meetings and pre-meeting returns.' },
  { id: USR.karenFindlay, givenName: 'Karen', familyName: 'Findlay', agency: 'social-work', roleId: 'marac-coordinator', jobTitle: 'MARAC Coordinator', organisationId: ORG.council, teamId: TEAM.publicProtectionCouncil, base: 'Ardvale Civic Centre', processMemberships: ['marac'], blurb: 'Runs the fortnightly Clydeshore MARAC.' },
  { id: USR.davidLaird, givenName: 'David', familyName: 'Laird', agency: 'social-work', roleId: 'chair', jobTitle: 'Independent reviewing officer and CP chair', organisationId: ORG.council, teamId: TEAM.reviewing, base: 'Ardvale Civic Centre', processMemberships: ['cp', 'asp'], blurb: 'Chairs CPPMs and ASP case conferences.' },
  { id: USR.lesleyMorton, givenName: 'Lesley', familyName: 'Morton', agency: 'social-work', roleId: 'minute-taker', jobTitle: 'Public protection administrator', organisationId: ORG.council, teamId: TEAM.reviewing, base: 'Ardvale Civic Centre', processMemberships: ['cp', 'asp', 'marac', 'mappa'], blurb: 'Minutes meetings and distributes packs.' },
  { id: USR.markHepburn, givenName: 'Mark', familyName: 'Hepburn', agency: 'housing', roleId: 'housing-officer', jobTitle: 'Housing officer', organisationId: ORG.council, teamId: TEAM.housing, base: 'Ardvale Housing Office', processMemberships: ['marac', 'mappa', 'asp'], blurb: 'Tenancy and MAPPA accommodation liaison.' },
  { id: USR.claireCowan, givenName: 'Claire', familyName: 'Cowan', agency: 'education', roleId: 'education-cp-lead', jobTitle: 'Head teacher, Ardvale Primary', organisationId: ORG.council, teamId: TEAM.ardvalePrimary, base: 'Ardvale Primary School', processMemberships: ['cp'], blurb: 'Named person and designated child protection lead for Aiden Boyle.' },
  { id: USR.andrewMuirhead, givenName: 'Andrew', familyName: 'Muirhead', agency: 'social-work', roleId: 'cswo', jobTitle: 'Chief Social Work Officer', organisationId: ORG.council, teamId: TEAM.cswo, base: 'Ardvale Civic Centre', processMemberships: ['asp', 'cp', 'marac', 'mappa', 'awi'], blurb: 'Oversight and sign-off across all processes.' },
  { id: USR.samOgilvie, givenName: 'Sam', familyName: 'Ogilvie', agency: 'social-work', roleId: 'system-administrator', jobTitle: 'System administrator', organisationId: ORG.council, teamId: TEAM.admin, base: 'Ardvale Civic Centre', processMemberships: [], blurb: 'Configuration, need-to-know matrices, connectors. No case content.' },
  { id: USR.elspethGunn, givenName: 'Elspeth', familyName: 'Gunn', agency: 'social-work', roleId: 'apc-lead-officer', jobTitle: 'Adult Protection Committee lead officer', organisationId: ORG.council, teamId: TEAM.apc, base: 'Ardvale Civic Centre', processMemberships: ['asp'], blurb: 'Biennial report and Learning Reviews.' },
  { id: USR.neilBaird, givenName: 'Neil', familyName: 'Baird', agency: 'social-work', roleId: 'cpc-lead-officer', jobTitle: 'Child Protection Committee lead officer', organisationId: ORG.council, teamId: TEAM.cpc, base: 'Ardvale Civic Centre', processMemberships: ['cp'], blurb: 'Register statistics and quality assurance.' },
  { id: USR.paulMackay, givenName: 'Paul', familyName: 'Mackay', agency: 'police', roleId: 'detective-sergeant-ppu', jobTitle: 'Detective Sergeant, Public Protection Unit', organisationId: ORG.police, teamId: TEAM.ppu, base: 'Ardvale Police Station', processMemberships: ['cp', 'asp', 'marac'], blurb: 'Police decision maker at IRDs; leads criminal investigations.', featured: true },
  { id: USR.ewanSutherland, givenName: 'Ewan', familyName: 'Sutherland', agency: 'police', roleId: 'domestic-abuse-officer', jobTitle: 'Detective Constable, Domestic Abuse Investigation Unit', organisationId: ORG.police, teamId: TEAM.dau, base: 'Ardvale Police Station', processMemberships: ['marac'], blurb: 'Referred Kayleigh Docherty to MARAC after the DAQ.' },
  { id: USR.priyaSharif, givenName: 'Priya', familyName: 'Sharif', agency: 'police', roleId: 'offender-management', jobTitle: 'Sex offender liaison officer', organisationId: ORG.police, teamId: TEAM.som, base: 'Kilbrannan Police Station', processMemberships: ['mappa'], blurb: 'Lead Responsible Authority contact for Derek Muir.' },
  { id: USR.gavinBrodie, givenName: 'Gavin', familyName: 'Brodie', agency: 'police', roleId: 'concern-hub-officer', jobTitle: 'Concern hub officer', organisationId: ORG.police, teamId: TEAM.concernHub, base: 'Ardvale Police Station', processMemberships: ['cp', 'asp'], blurb: 'Triage of iVPD child and adult concern reports.' },
  { id: USR.fionaRoss, givenName: 'Fiona', familyName: 'Ross', agency: 'health', roleId: 'cp-nurse-adviser', jobTitle: 'Child protection nurse adviser', organisationId: ORG.nhs, teamId: TEAM.cpHealth, base: 'Clydeshore Royal Infirmary', processMemberships: ['cp'], blurb: 'Health decision maker at IRDs; arranges medicals.', featured: true },
  { id: USR.amiraFarouk, givenName: 'Amira', familyName: 'Farouk', agency: 'health', roleId: 'gp', jobTitle: 'GP, Portnellan Medical Practice', organisationId: ORG.nhs, teamId: TEAM.portnellanGp, base: 'Portnellan Medical Practice', processMemberships: ['asp', 'awi', 'cp', 'marac'], blurb: 'GP for Marion Fraser and the Docherty family.' },
  { id: USR.sunitaRao, givenName: 'Sunita', familyName: 'Rao', agency: 'health', roleId: 'health-visitor', jobTitle: 'Health visitor', organisationId: ORG.nhs, teamId: TEAM.healthVisiting, base: 'Braeside Health Centre', processMemberships: ['cp', 'marac'], blurb: 'Named person for Maisie Boyle and Mason Docherty.' },
  { id: USR.kasiaNowicka, givenName: 'Kasia', familyName: 'Nowicka', agency: 'health', roleId: 'midwife', jobTitle: 'Community midwife', organisationId: ORG.nhs, teamId: TEAM.midwifery, base: 'Clydeshore Royal Infirmary', processMemberships: ['cp', 'marac'], blurb: 'Midwife for Chloe Reid.' },
  { id: USR.louiseKennedy, givenName: 'Louise', familyName: 'Kennedy', agency: 'health', roleId: 'cmhn', jobTitle: 'Community mental health nurse', organisationId: ORG.nhs, teamId: TEAM.cmht, base: 'Kilbrannan Health and Care Hub', processMemberships: ['asp', 'awi', 'mappa'], blurb: 'Health board single point of contact for MAPPA.' },
  { id: USR.heatherAitken, givenName: 'Heather', familyName: 'Aitken', agency: 'health', roleId: 'discharge-coordinator', jobTitle: 'Hospital discharge coordinator', organisationId: ORG.nhs, teamId: TEAM.discharge, base: 'Clydeshore Royal Infirmary', processMemberships: ['awi'], blurb: 'Delayed discharge for Ishbel Grant.' },
  { id: USR.niallFyfe, givenName: 'Niall', familyName: 'Fyfe', agency: 'health', roleId: 'caldicott-guardian', jobTitle: 'Caldicott guardian', organisationId: ORG.nhs, teamId: TEAM.caldicott, base: 'NHS Clydeshore Headquarters', processMemberships: [], blurb: 'Audit view of health information shared. No case content.' },
  { id: USR.sadiaQureshi, givenName: 'Sadia', familyName: 'Qureshi', agency: 'third-sector', roleId: 'idaa', jobTitle: 'Independent Domestic Abuse Advocate', organisationId: ORG.womensAid, teamId: TEAM.womensAid, base: 'Ardvale (confidential address)', processMemberships: ['marac'], blurb: "Represents Kayleigh Docherty's wishes at MARAC.", featured: true },
  { id: USR.erinLamont, givenName: 'Erin', familyName: 'Lamont', agency: 'third-sector', roleId: 'womens-aid-worker', jobTitle: "Women's Aid support worker", organisationId: ORG.womensAid, teamId: TEAM.womensAid, base: 'Ardvale (confidential address)', processMemberships: ['marac'], blurb: 'Refuge and outreach support.' },
  { id: USR.tamGuthrie, givenName: 'Tam', familyName: 'Guthrie', agency: 'third-sector', roleId: 'independent-advocate', jobTitle: 'Independent advocate', organisationId: ORG.advocacy, teamId: TEAM.advocacy, base: 'Kilbrannan', processMemberships: ['asp', 'awi'], blurb: 'Advocate for Marion Fraser and Tomasz Nowak.' },
  { id: USR.colinBeattie, givenName: 'Colin', familyName: 'Beattie', agency: 'sps', roleId: 'prison-social-worker', jobTitle: 'Prison-based social worker', organisationId: ORG.sps, teamId: TEAM.spsSocialWork, base: 'HMP Glenmoray', processMemberships: ['mappa', 'marac'], blurb: 'Pre-release planning for MAPPA cases.' },
  { id: USR.rhonaDewar, givenName: 'Rhona', familyName: 'Dewar', agency: 'regulator', roleId: 'inspector', jobTitle: 'Inspector, joint inspection', organisationId: ORG.careInspectorate, teamId: TEAM.inspection, base: 'Care Inspectorate', processMemberships: ['asp', 'cp', 'marac', 'mappa', 'awi'], blurb: 'Read-only, redacted view for inspection.' },
  { id: USR.islaCrawford, givenName: 'Isla', familyName: 'Crawford', agency: 'scra', roleId: 'reporter', jobTitle: "Children's Reporter", organisationId: ORG.scra, teamId: TEAM.scra, base: 'Ardvale', processMemberships: ['cp'], blurb: 'Receives referral decisions from IRDs and CPPMs.' },
  { id: USR.morvenTait, givenName: 'Morven', familyName: 'Tait', agency: 'regulator', roleId: 'care-inspectorate-officer', jobTitle: 'Inspector, adult services', organisationId: ORG.careInspectorate, teamId: TEAM.ci, base: 'Care Inspectorate', processMemberships: ['asp'], blurb: 'Rowanbank Care Home Large Scale Investigation.' },
  { id: USR.alistairMeek, givenName: 'Alistair', familyName: 'Meek', agency: 'regulator', roleId: 'opg-officer', jobTitle: 'Investigations officer, OPG', organisationId: ORG.opg, teamId: TEAM.opg, base: 'Office of the Public Guardian', processMemberships: ['awi', 'asp'], blurb: 'Register checks and financial harm investigations.' },
  { id: USR.jeanHogg, givenName: 'Jean', familyName: 'Hogg', agency: 'regulator', roleId: 'mwc-officer', jobTitle: 'Practitioner, Mental Welfare Commission', organisationId: ORG.mwc, teamId: TEAM.mwc, base: 'Mental Welfare Commission', processMemberships: ['awi'], blurb: 'Welfare guardianship notifications.' },
  { id: USR.gordonNairn, givenName: 'Gordon', familyName: 'Nairn', agency: 'fire-rescue', roleId: 'fire-safety-officer', jobTitle: 'Community safety officer', organisationId: ORG.fire, teamId: TEAM.fire, base: 'Glenmoray Fire Station', processMemberships: ['asp'], blurb: 'Raised the fire risk concern for Tomasz Nowak.' },
  { id: USR.fionaLyle, givenName: 'Fiona', familyName: 'Lyle', agency: 'court', roleId: 'procurator-fiscal', jobTitle: 'Procurator fiscal depute', organisationId: ORG.cops, teamId: TEAM.pf, base: 'Ardvale Sheriff Court', processMemberships: ['cp'], blurb: 'JII and prosecution decisions.' },
];

export function seedOrganisations(ctx: BuildContext): void {
  ctx.data.organisations.push(...organisations);
  ctx.data.teams.push(...teams);
  for (const s of seeds) {
    const user: User = {
      ...s,
      synthetic: true,
      email: email(s.givenName, s.familyName, s.organisationId),
      phone: `01000 ${ctx.rng.int(200000, 899999)}`,
      caseMemberships: s.caseMemberships ?? [],
    };
    ctx.data.users.push(user);
  }
}

export function userName(ctx: BuildContext, id: string): string {
  const u = ctx.user(id);
  return `${u.givenName} ${u.familyName}`;
}
