import type { ClockRule } from '../schemas/config';

/**
 * Statutory and local clock rules. Values come from docs/RESEARCH.md.
 * Rules marked `todoVerify` were seeded from search extracts or local procedures
 * rather than read in the primary source; Admin shows their confidence.
 */
export const CLOCK_RULES: ClockRule[] = [
  {
    id: 'cp.cppm.initial',
    process: 'cp',
    label: 'Initial Child Protection Planning Meeting',
    trigger: 'Child protection procedures initiated (IRD)',
    unit: 'calendar-days',
    amount: 28,
    kind: 'deadline',
    warnDays: 7,
    source: 'National Guidance for Child Protection in Scotland 2021 (updated 2023), Part 3',
    sourceRef: 'Within 28 calendar days of the concern being raised, unless the IRD decides a CPPM is not required',
    confidence: 'high',
  },
  {
    id: 'cp.coregroup.first',
    process: 'cp',
    label: 'First core group meeting',
    trigger: 'Initial CPPM held',
    unit: 'working-days',
    amount: 15,
    kind: 'deadline',
    warnDays: 5,
    source: 'National Guidance for Child Protection in Scotland 2021, Appendix D',
    sourceRef: 'Within 15 working days of the CPPM',
    confidence: 'high',
  },
  {
    id: 'cp.cppm.review.first',
    process: 'cp',
    label: 'First review CPPM',
    trigger: 'Initial CPPM held',
    unit: 'months',
    amount: 6,
    kind: 'review',
    warnDays: 21,
    source: 'National Guidance for Child Protection in Scotland 2021, Appendix D',
    sourceRef: 'Within 6 months of the initial CPPM (Appendix D). A review may be brought forward on significant change without altering the statutory maximum',
    confidence: 'high',
  },
  {
    id: 'cp.cppm.review.subsequent',
    process: 'cp',
    label: 'Subsequent review CPPM',
    trigger: 'Review CPPM held',
    unit: 'months',
    amount: 6,
    kind: 'review',
    warnDays: 21,
    source: 'National Guidance for Child Protection in Scotland 2021, Appendix D',
    sourceRef: 'At least every 6 months, or earlier on significant change',
    confidence: 'high',
  },
  {
    id: 'cp.cppm.notice',
    process: 'cp',
    label: 'Notice of the CPPM to family and invitees',
    trigger: 'CPPM date set (the clock counts back from the meeting date)',
    unit: 'calendar-days',
    amount: 5,
    direction: 'before',
    kind: 'deadline',
    warnDays: 2,
    source: 'National Guidance for Child Protection in Scotland 2021, Part 3 (invitations, reports and the family being told in advance)',
    sourceRef: 'Invitations and reports no later than 5 calendar days before the CPPM; value supplied by the product owner on 03 Sep 2026, to verify against the national guidance and the local procedures',
    confidence: 'verify',
    todoVerify: true,
  },
  {
    id: 'cp.coregroup.escalate',
    process: 'cp',
    label: 'Core group concern escalated to the chair',
    trigger: 'Core group unable to agree, or a concern raised that the plan is not working',
    unit: 'calendar-days',
    amount: 3,
    kind: 'deadline',
    warnDays: 1,
    source: 'Local procedures (the national guidance requires escalation to the lead professional and the CPPM chair without setting a timescale)',
    sourceRef: 'Within 3 calendar days; value supplied by the product owner on 03 Sep 2026, to verify against the local procedures',
    confidence: 'local',
    todoVerify: true,
  },
  {
    id: 'cp.prebirth.review',
    process: 'cp',
    label: 'Post-birth review of a pre-birth plan',
    trigger: 'Birth of the baby',
    unit: 'months',
    amount: 3,
    kind: 'review',
    warnDays: 21,
    source: 'National Guidance for Child Protection in Scotland 2021, Appendix D (review within 3 months of the pre-birth CPPM, with latitude after the birth)',
    sourceRef: 'Advisory: a review within 3 months of the birth so the plan is tested against the child as born; value supplied by the product owner on 03 Sep 2026',
    confidence: 'advisory',
  },
  {
    id: 'cp.prebirth.cppm',
    process: 'cp',
    label: 'Pre-birth CPPM',
    trigger: 'Pre-birth concern raised',
    unit: 'calendar-days',
    amount: 28,
    kind: 'deadline',
    warnDays: 7,
    source: 'National Guidance for Child Protection in Scotland 2021, Part 4 (unborn babies)',
    sourceRef: 'Within 28 calendar days of the concern and no later than 28 weeks gestation. The gestation cap is applied as a due date override on the process',
    confidence: 'high',
  },
  {
    id: 'asp.inquiry.decision',
    process: 'asp',
    label: 'Inquiry decision',
    trigger: 'Adult concern received',
    unit: 'working-days',
    amount: 5,
    kind: 'deadline',
    warnDays: 2,
    source: 'Local procedures (the Code of Practice 2022 sets no national timescale)',
    sourceRef: 'West of Scotland inter-agency guidance and Edinburgh 2024 procedures use 5 working days',
    confidence: 'local',
    localNote: 'Clydeshore ASP procedures: 5 working days',
    todoVerify: true,
  },
  {
    id: 'asp.caseconference.initial',
    process: 'asp',
    label: 'Initial ASP case conference',
    trigger: 'Adult concern received',
    unit: 'calendar-days',
    amount: 21,
    kind: 'deadline',
    warnDays: 7,
    source: 'Local procedures (the Code of Practice 2022 sets no national timescale)',
    sourceRef: 'Highland 21 days; Orkney 20 days; Renfrewshire 20 working days',
    confidence: 'local',
    localNote: 'Clydeshore ASP procedures: 21 calendar days',
    todoVerify: true,
  },
  {
    id: 'asp.plan.review',
    process: 'asp',
    label: 'Adult Protection Plan review',
    trigger: 'Protection plan agreed',
    unit: 'months',
    amount: 3,
    kind: 'review',
    warnDays: 14,
    source: 'Local procedures',
    sourceRef: 'South Lanarkshire and Dumfries and Galloway review at 3 months then three monthly',
    confidence: 'local',
    todoVerify: true,
  },
  {
    id: 'marac.research.return',
    process: 'marac',
    label: 'MARAC research return',
    trigger: 'Research request sent',
    unit: 'working-days',
    amount: 5,
    kind: 'deadline',
    warnDays: 2,
    source: 'Local MARAC Operating Protocol (SafeLives sets no national deadline)',
    sourceRef: 'SafeLives: case list circulated about 8 working days before the meeting; the return window is local',
    confidence: 'local',
    localNote: 'Clydeshore MARAC Operating Protocol: returns 5 working days before the meeting',
    todoVerify: true,
  },
  {
    id: 'marac.flag.expiry',
    process: 'marac',
    label: 'MARAC flag expiry',
    trigger: 'Case heard at MARAC',
    unit: 'months',
    amount: 12,
    kind: 'expiry',
    warnDays: 30,
    source: 'SafeLives MARAC practice',
    sourceRef: 'Flag on agency records for 12 months from the last referral',
    confidence: 'high',
  },
  {
    id: 'marac.repeat.window',
    process: 'marac',
    label: 'MARAC repeat window',
    trigger: 'Case heard at MARAC',
    unit: 'months',
    amount: 12,
    kind: 'expiry',
    warnDays: 0,
    source: 'SafeLives MARAC definitions',
    sourceRef: 'A repeat is a further referral within 12 months of the last referral',
    confidence: 'high',
  },
  {
    id: 'mappa.level2.review',
    process: 'mappa',
    label: 'MAPPA Level 2 review',
    trigger: 'Level 2 meeting held',
    unit: 'weeks',
    amount: 12,
    kind: 'review',
    warnDays: 14,
    source: 'MAPPA National Guidance 2022 (refreshed 31 March 2022)',
    sourceRef: 'Level 2 cases reviewed no less than once every 12 weeks',
    confidence: 'high',
  },
  {
    id: 'mappa.level3.review',
    process: 'mappa',
    label: 'MAPPA Level 3 review',
    trigger: 'Level 3 (MAPPP) meeting held',
    unit: 'weeks',
    amount: 6,
    kind: 'review',
    warnDays: 10,
    source: 'MAPPA National Guidance 2022 (refreshed 31 March 2022)',
    sourceRef: 'Level 3 cases reviewed no less than once every 6 weeks',
    confidence: 'high',
  },
  {
    id: 'awi.mho.report',
    process: 'awi',
    label: 'MHO report',
    trigger: 'MHO notified of guardianship application',
    unit: 'calendar-days',
    amount: 21,
    kind: 'deadline',
    warnDays: 7,
    source: 'Adults with Incapacity (Scotland) Act 2000 s57(4)',
    sourceRef: 'Report within 21 days of the date of notice',
    confidence: 'high',
  },
  {
    id: 'awi.interim.warning',
    process: 'awi',
    label: 'Interim guardianship order duration',
    trigger: 'Interim order granted',
    unit: 'months',
    amount: 3,
    kind: 'warning',
    warnDays: 14,
    source: 'Adults with Incapacity (Scotland) Act 2000 s57 as amended by ASP Act 2007 s60',
    sourceRef: 'Interim orders run for 3 months by default and cannot exceed 6 months in total. The Expert Working Group (2025 to 2026) has raised concerns about prolonged interim orders',
    confidence: 'high',
  },
  {
    id: 'awi.interim.maximum',
    process: 'awi',
    label: 'Interim order statutory maximum',
    trigger: 'Interim order granted',
    unit: 'months',
    amount: 6,
    kind: 'expiry',
    warnDays: 21,
    source: 'Adults with Incapacity (Scotland) Act 2000 s57 as amended',
    sourceRef: 'Total interim period cannot exceed 6 months',
    confidence: 'high',
  },
];

export function findClockRule(rules: ClockRule[], id: string): ClockRule | undefined {
  return rules.find((r) => r.id === id);
}
