import type { NeedToKnowRow } from '../schemas/config';

const LB_ASP = 'ASP (Scotland) Act 2007 s5 duty to cooperate; UK GDPR 6(1)(c) and 9(2)(g) with DPA 2018 Sch 1 Pt 2 para 18';

export const ASP_ROWS: NeedToKnowRow[] = [
  { id: 'asp.concern.duty', process: 'asp', stage: 'concern', audience: { agency: 'social-work', role: 'team-leader', label: 'Council duty team' }, detailLevel: 'full', channel: 'in-app', trigger: 'Adult concern recorded', lawfulBasisHint: LB_ASP },
  { id: 'asp.concern.co', process: 'asp', stage: 'concern', audience: { agency: 'social-work', role: 'council-officer-asp', label: 'Council officer' }, detailLevel: 'full', channel: 'in-app', trigger: 'Adult concern recorded', lawfulBasisHint: LB_ASP },
  { id: 'asp.concern.referrer', process: 'asp', stage: 'concern', audience: { agency: 'referrer', role: 'any', label: 'Referrer (acknowledgement and outcome only)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Adult concern recorded', lawfulBasisHint: 'Acknowledgement only; no detail is shared with the referrer' },
  { id: 'asp.inquiry.co', process: 'asp', stage: 'inquiry', audience: { agency: 'social-work', role: 'council-officer-asp', label: 'Council officer' }, detailLevel: 'full', channel: 'in-app', trigger: 'Inquiry opened', lawfulBasisHint: LB_ASP },
  { id: 'asp.inquiry.tl', process: 'asp', stage: 'inquiry', audience: { agency: 'social-work', role: 'team-leader', label: 'Team leader' }, detailLevel: 'full', channel: 'in-app', trigger: 'Inquiry opened', lawfulBasisHint: LB_ASP },
  { id: 'asp.inquiry.police', process: 'asp', stage: 'inquiry', audience: { agency: 'police', role: 'any', label: 'Police Scotland (criminal element)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Inquiry opened', condition: 'criminalElement', conditionLabel: 'If there is a criminal element', lawfulBasisHint: LB_ASP },
  { id: 'asp.inquiry.gp', process: 'asp', stage: 'inquiry', audience: { agency: 'health', role: 'gp', label: 'GP (health input)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Inquiry opened', condition: 'healthInput', conditionLabel: 'If health input is needed', lawfulBasisHint: LB_ASP + '; Caldicott principles' },
  { id: 'asp.inquiry.cmhn', process: 'asp', stage: 'inquiry', audience: { agency: 'health', role: 'cmhn', label: 'Community nurse (health input)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Inquiry opened', condition: 'healthInput', conditionLabel: 'If health input is needed', lawfulBasisHint: LB_ASP + '; Caldicott principles' },
  { id: 'asp.inquiry.provider', process: 'asp', stage: 'inquiry', audience: { agency: 'third-sector', role: 'any', label: 'Care provider (regulated service)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Inquiry opened', condition: 'regulatedService', conditionLabel: 'If a regulated service is involved', lawfulBasisHint: LB_ASP },
  { id: 'asp.inquiry.housing', process: 'asp', stage: 'inquiry', audience: { agency: 'housing', role: 'any', label: 'Housing' }, detailLevel: 'summary', channel: 'in-app', trigger: 'Inquiry opened', condition: 'housingRelevant', conditionLabel: 'If housing is relevant', lawfulBasisHint: LB_ASP },
  { id: 'asp.investigation.co', process: 'asp', stage: 'investigation', audience: { agency: 'social-work', role: 'council-officer-asp', label: 'Council officer and second worker' }, detailLevel: 'full', channel: 'in-app', trigger: 'Investigation opened', lawfulBasisHint: LB_ASP },
  { id: 'asp.investigation.police', process: 'asp', stage: 'investigation', audience: { agency: 'police', role: 'any', label: 'Police (joint visit)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Investigation opened', condition: 'jointVisit', conditionLabel: 'If a joint visit is planned', lawfulBasisHint: LB_ASP },
  { id: 'asp.investigation.medical', process: 'asp', stage: 'investigation', audience: { agency: 'health', role: 'gp', label: 'Health (s9 medical examination)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Investigation opened', condition: 'medicalExamination', conditionLabel: 'If a s9 medical examination is arranged', lawfulBasisHint: LB_ASP + '; s9' },
  { id: 'asp.investigation.records', process: 'asp', stage: 'investigation', audience: { agency: 'health', role: 'gp', label: 'Records holder (s10 request)' }, detailLevel: 'fields', fields: ['s10 records request', 'purpose of request', 'council officer contact'], channel: 'in-app', trigger: 's10 records request sent', condition: 'recordsRequest', conditionLabel: 'If records are requested under s10', lawfulBasisHint: 'ASP (Scotland) Act 2007 s10; a health professional inspects health records' },
  { id: 'asp.investigation.advocacy', process: 'asp', stage: 'investigation', audience: { agency: 'third-sector', role: 'independent-advocate', label: 'Advocacy service' }, detailLevel: 'summary', channel: 'in-app', trigger: 'Advocacy offered', condition: 'advocacyOffered', conditionLabel: 'If advocacy has been offered', lawfulBasisHint: LB_ASP + '; ASP s6 advocacy' },
  { id: 'asp.investigation.opg', process: 'asp', stage: 'investigation', audience: { agency: 'regulator', role: 'opg-officer', label: 'OPG (financial harm or attorney conduct)' }, detailLevel: 'fields', fields: ['adult name and date of birth', 'nature of financial concern', 'whether a power of attorney or guardianship exists'], channel: 'secure-email-digest', trigger: 'Financial harm identified', condition: 'financialHarm', conditionLabel: 'If financial harm or attorney or guardian conduct is in question', lawfulBasisHint: LB_ASP + '; OPG duty to cooperate' },
  { id: 'asp.conference.chair', process: 'asp', stage: 'case-conference', audience: { agency: 'social-work', role: 'chair', label: 'Chair' }, detailLevel: 'full', channel: 'in-app', trigger: 'Case conference scheduled', lawfulBasisHint: LB_ASP },
  { id: 'asp.conference.minutes', process: 'asp', stage: 'case-conference', audience: { agency: 'social-work', role: 'minute-taker', label: 'Minute taker' }, detailLevel: 'full', channel: 'in-app', trigger: 'Case conference scheduled', lawfulBasisHint: LB_ASP },
  { id: 'asp.conference.advocate', process: 'asp', stage: 'case-conference', audience: { agency: 'third-sector', role: 'independent-advocate', label: 'Adult and advocate' }, detailLevel: 'full', channel: 'in-app', trigger: 'Case conference scheduled', condition: 'advocacyOffered', conditionLabel: 'If an advocate is involved', lawfulBasisHint: LB_ASP },
  { id: 'asp.conference.ci', process: 'asp', stage: 'case-conference', audience: { agency: 'regulator', role: 'care-inspectorate-officer', label: 'Care Inspectorate (regulated service)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Case conference scheduled', condition: 'regulatedService', conditionLabel: 'If a regulated service is involved', lawfulBasisHint: LB_ASP },
  { id: 'asp.conference.mwc', process: 'asp', stage: 'case-conference', audience: { agency: 'regulator', role: 'mwc-officer', label: 'MWC (welfare concerns about guardian or attorney)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Case conference scheduled', condition: 'guardianConcern', conditionLabel: 'If there are welfare concerns about a guardian or attorney', lawfulBasisHint: LB_ASP },
  { id: 'asp.plan.advocate', process: 'asp', stage: 'protection-plan', audience: { agency: 'third-sector', role: 'independent-advocate', label: 'Adult and advocate' }, detailLevel: 'full', channel: 'in-app', trigger: 'Protection plan agreed', condition: 'advocacyOffered', conditionLabel: 'If an advocate is involved', lawfulBasisHint: LB_ASP },
  { id: 'asp.plan.referrer', process: 'asp', stage: 'protection-plan', audience: { agency: 'referrer', role: 'any', label: 'Referrer (outcome)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Protection plan agreed', lawfulBasisHint: 'Outcome only' },
  { id: 'asp.support.referrer', process: 'asp', stage: 'support-plan', audience: { agency: 'referrer', role: 'any', label: 'Referrer (outcome)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Support plan agreed', lawfulBasisHint: 'Outcome only' },
  { id: 'asp.review.chair', process: 'asp', stage: 'review', audience: { agency: 'social-work', role: 'chair', label: 'Chair' }, detailLevel: 'full', channel: 'in-app', trigger: 'Review conference scheduled', lawfulBasisHint: LB_ASP },
  { id: 'asp.closed.contributors', process: 'asp', stage: 'closed', audience: { agency: 'referrer', role: 'any', label: 'Contributing agencies (closure notice)' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Case closed', lawfulBasisHint: 'Closure notice only' },
];
