import type { NeedToKnowRow } from '../schemas/config';

const LB_AWI = 'Adults with Incapacity (Scotland) Act 2000; UK GDPR 6(1)(c) and 9(2)(h) health and social care';

export const AWI_ROWS: NeedToKnowRow[] = [
  { id: 'awi.concern.worker', process: 'awi', stage: 'capacity-concern', audience: { agency: 'social-work', role: 'social-worker-adults', label: 'Allocated worker' }, detailLevel: 'full', channel: 'in-app', trigger: 'Capacity concern raised', lawfulBasisHint: LB_AWI },
  { id: 'awi.concern.mho', process: 'awi', stage: 'capacity-concern', audience: { agency: 'social-work', role: 'mho', label: 'MHO (welfare guardianship likely)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Capacity concern raised', condition: 'welfareGuardianshipLikely', conditionLabel: 'If welfare guardianship is likely', lawfulBasisHint: LB_AWI + '; s57(3)' },
  { id: 'awi.concern.gp', process: 'awi', stage: 'capacity-concern', audience: { agency: 'health', role: 'gp', label: 'GP or consultant' }, detailLevel: 'full', channel: 'in-app', trigger: 'Capacity concern raised', lawfulBasisHint: LB_AWI + '; Caldicott principles' },
  { id: 'awi.concern.discharge', process: 'awi', stage: 'capacity-concern', audience: { agency: 'health', role: 'discharge-coordinator', label: 'Discharge team' }, detailLevel: 'summary', channel: 'in-app', trigger: 'Capacity concern raised', condition: 'inHospital', conditionLabel: 'If the adult is in hospital', lawfulBasisHint: LB_AWI },
  { id: 'awi.concern.provider', process: 'awi', stage: 'capacity-concern', audience: { agency: 'third-sector', role: 'any', label: 'Care provider' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Capacity concern raised', condition: 'careProvider', conditionLabel: 'If a care provider is involved', lawfulBasisHint: LB_AWI },
  { id: 'awi.powers.worker', process: 'awi', stage: 'existing-powers', audience: { agency: 'social-work', role: 'social-worker-adults', label: 'Worker' }, detailLevel: 'full', channel: 'in-app', trigger: 'OPG check made', lawfulBasisHint: LB_AWI },
  { id: 'awi.powers.opg', process: 'awi', stage: 'existing-powers', audience: { agency: 'regulator', role: 'opg-officer', label: 'OPG register' }, detailLevel: 'fields', fields: ['register result', 'adult name and date of birth'], channel: 'connector-push', trigger: 'OPG check made', lawfulBasisHint: LB_AWI + '; OPG register' },
  { id: 'awi.application.mho', process: 'awi', stage: 'application', audience: { agency: 'social-work', role: 'mho', label: 'MHO' }, detailLevel: 'full', channel: 'in-app', trigger: 'Application notified', lawfulBasisHint: LB_AWI + '; s57(3) and (4)' },
  { id: 'awi.application.gp', process: 'awi', stage: 'application', audience: { agency: 'health', role: 'gp', label: 'Medical practitioners' }, detailLevel: 'full', channel: 'in-app', trigger: 'Medical reports requested', lawfulBasisHint: LB_AWI + '; s57(3)' },
  { id: 'awi.application.court', process: 'awi', stage: 'application', audience: { agency: 'court', role: 'any', label: 'Sheriff court' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Application lodged', lawfulBasisHint: LB_AWI + '; Part 6' },
  { id: 'awi.application.advocate', process: 'awi', stage: 'application', audience: { agency: 'third-sector', role: 'independent-advocate', label: 'Independent advocate (notification and rights)' }, detailLevel: 'summary', channel: 'in-app', trigger: 'Application notified', lawfulBasisHint: LB_AWI },
  { id: 'awi.order.supervising', process: 'awi', stage: 'order', audience: { agency: 'social-work', role: 'social-worker-adults', label: 'Supervising officer' }, detailLevel: 'full', channel: 'in-app', trigger: 'Order granted', lawfulBasisHint: LB_AWI + '; s10' },
  { id: 'awi.order.opg', process: 'awi', stage: 'order', audience: { agency: 'regulator', role: 'opg-officer', label: 'OPG' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Order granted', lawfulBasisHint: LB_AWI + '; registration' },
  { id: 'awi.order.mwc', process: 'awi', stage: 'order', audience: { agency: 'regulator', role: 'mwc-officer', label: 'MWC' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Order granted', lawfulBasisHint: LB_AWI + '; notification' },
  { id: 'awi.order.provider', process: 'awi', stage: 'order', audience: { agency: 'third-sector', role: 'any', label: 'Care provider' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Order granted', condition: 'careProvider', conditionLabel: 'If a care provider is involved', lawfulBasisHint: LB_AWI },
  { id: 'awi.order.gp', process: 'awi', stage: 'order', audience: { agency: 'health', role: 'gp', label: 'GP' }, detailLevel: 'summary', channel: 'secure-email-digest', trigger: 'Order granted', lawfulBasisHint: LB_AWI },
  { id: 'awi.supervision.officer', process: 'awi', stage: 'supervision', audience: { agency: 'social-work', role: 'social-worker-adults', label: 'Supervising officer' }, detailLevel: 'full', channel: 'in-app', trigger: 'Supervision scheduled', lawfulBasisHint: LB_AWI + '; s10' },
  { id: 'awi.supervision.mwc', process: 'awi', stage: 'supervision', audience: { agency: 'regulator', role: 'mwc-officer', label: 'MWC (welfare)' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Investigation opened', condition: 'welfareInvestigation', conditionLabel: 'If a welfare investigation is open', lawfulBasisHint: LB_AWI },
  { id: 'awi.supervision.opg', process: 'awi', stage: 'supervision', audience: { agency: 'regulator', role: 'opg-officer', label: 'OPG (financial)' }, detailLevel: 'full', channel: 'secure-email-digest', trigger: 'Investigation opened', condition: 'financialInvestigation', conditionLabel: 'If a financial investigation is open', lawfulBasisHint: LB_AWI },
];
