import type { NeedToKnowRow } from '../schemas/config';

const LB_MAPPA = 'Management of Offenders etc. (Scotland) Act 2005 s10; MAPPA National Guidance 2022; UK GDPR 6(1)(c) and 9(2)(g); DPA 2018 s10 and Sch 1 (offence data)';

export const MAPPA_ROWS: NeedToKnowRow[] = [
  { id: 'mappa.notification.police', process: 'mappa', stage: 'notification', audience: { agency: 'police', role: 'offender-management', label: 'Police offender management (lead RA)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Notification received', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.notification.jsw', process: 'mappa', stage: 'notification', audience: { agency: 'social-work', role: 'justice-social-worker', label: 'Justice social work (lead RA where under supervision)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Notification received', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.notification.coordinator', process: 'mappa', stage: 'notification', audience: { agency: 'social-work', role: 'mappa-coordinator', label: 'MAPPA Coordinator' }, detailLevel: 'full', channel: 'in-app', trigger: 'Notification received', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.notification.health', process: 'mappa', stage: 'notification', audience: { agency: 'health', role: 'cmhn', label: 'Health board (Responsible Authority, presence)' }, detailLevel: 'presence', channel: 'in-app', trigger: 'Notification received', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.notification.sps', process: 'mappa', stage: 'notification', audience: { agency: 'sps', role: 'prison-social-worker', label: 'SPS (Responsible Authority, presence)' }, detailLevel: 'presence', channel: 'in-app', trigger: 'Notification received', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.coordinator', process: 'mappa', stage: 'referral', audience: { agency: 'social-work', role: 'mappa-coordinator', label: 'MAPPA Coordinator' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.spoc-police', process: 'mappa', stage: 'referral', audience: { agency: 'police', role: 'offender-management', label: 'Police single point of contact' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.spoc-jsw', process: 'mappa', stage: 'referral', audience: { agency: 'social-work', role: 'justice-social-worker', label: 'Council single point of contact' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.spoc-health', process: 'mappa', stage: 'referral', audience: { agency: 'health', role: 'cmhn', label: 'Health board single point of contact' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.spoc-sps', process: 'mappa', stage: 'referral', audience: { agency: 'sps', role: 'prison-social-worker', label: 'SPS single point of contact' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', condition: 'inCustody', conditionLabel: 'While the person is in custody', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.referral.spoc-housing', process: 'mappa', stage: 'referral', audience: { agency: 'housing', role: 'housing-officer', label: 'Housing (duty to cooperate)' }, detailLevel: 'full', channel: 'in-app', trigger: 'Referral to Level 2 or 3', condition: 'housingRelevant', conditionLabel: 'If accommodation is in question', lawfulBasisHint: LB_MAPPA + '; duty to cooperate' },
  { id: 'mappa.premeeting.coordinator', process: 'mappa', stage: 'pre-meeting', audience: { agency: 'social-work', role: 'mappa-coordinator', label: 'MAPPA Coordinator' }, detailLevel: 'full', channel: 'in-app', trigger: 'Returns requested', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.premeeting.chair', process: 'mappa', stage: 'pre-meeting', audience: { agency: 'police', role: 'offender-management', label: 'Chair' }, detailLevel: 'full', channel: 'in-app', trigger: 'Returns requested', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.meeting.members-summary', process: 'mappa', stage: 'managed', audience: { agency: 'social-work', role: 'justice-social-worker', label: 'Case members (level and review date)' }, detailLevel: 'summary', channel: 'in-app', trigger: 'Level decision recorded', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.meeting.housing-era', process: 'mappa', stage: 'managed', audience: { agency: 'housing', role: 'housing-officer', label: 'Housing (ERA conclusions and controls)' }, detailLevel: 'fields', fields: ['Environmental Risk Assessment conclusions', 'accommodation controls', 'contact for concerns'], channel: 'in-app', trigger: 'RMP agreed', condition: 'housingRelevant', conditionLabel: 'If accommodation is in question', lawfulBasisHint: LB_MAPPA + '; National Accommodation Strategy for Sex Offenders' },
  { id: 'mappa.meeting.csw-disclosure', process: 'mappa', stage: 'managed', audience: { agency: 'social-work', role: 'social-worker-children', label: "Children's social work (specific disclosure, child in household)" }, detailLevel: 'fields', fields: ['specific facts disclosed by decision', 'contact for concerns'], channel: 'in-app', trigger: 'Disclosure decision recorded', condition: 'childInHousehold', conditionLabel: 'If a child is in the household', lawfulBasisHint: LB_MAPPA + '; recorded disclosure decision' },
  { id: 'mappa.exit.ras', process: 'mappa', stage: 'exit', audience: { agency: 'police', role: 'offender-management', label: 'Responsible Authorities' }, detailLevel: 'full', channel: 'in-app', trigger: 'Exit recorded', lawfulBasisHint: LB_MAPPA },
  { id: 'mappa.exit.jsw', process: 'mappa', stage: 'exit', audience: { agency: 'social-work', role: 'justice-social-worker', label: 'Responsible Authorities' }, detailLevel: 'full', channel: 'in-app', trigger: 'Exit recorded', lawfulBasisHint: LB_MAPPA },
];
