/* Generated by `pnpm messages:types` from en-GB.json. Do not edit by hand. */

export type MessageKey =
  | 'common.actions.close'
  | 'common.app.loading'
  | 'common.app.name'
  | 'common.app.tagline'
  | 'common.app.titleWithScreen'
;

export interface MessageArgs {
  'common.actions.close': Record<string, never>;
  'common.app.loading': Record<string, never>;
  'common.app.name': Record<string, never>;
  'common.app.tagline': Record<string, never>;
  'common.app.titleWithScreen': { screen: string | number; app: string | number };
}

export const MESSAGE_KEYS: readonly MessageKey[] = ['common.actions.close', 'common.app.loading', 'common.app.name', 'common.app.tagline', 'common.app.titleWithScreen'];
